TableRise/tablerise-backend

- .github/workflows/project-card-moved.yml
> setup: Giving write access

- .github/pull_request_template.md
- .github/workflows/main.yml
- package.json
- scripts/checkCoverage.js
- src/controllers/ClassesControllers.ts
- src/controllers/SpellsControllers.ts
- src/services/ClassesServices.ts
- src/services/SpellsServices.ts
- test/unit/controllers/ClassesControllers.spec.ts
- test/unit/controllers/SpellsControllers.spec.ts
- test/unit/database/models/ItemsModel.spec.ts
- test/unit/services/ClassesServices.spec.ts
- test/unit/services/ItemsServices.spec.ts
- test/unit/services/RacesServices.spec.ts
- test/unit/services/SpellsServices.spec.ts
- test/unit/services/SystemServices.spec.ts
> #89 - Adjust tests to reach 100% of coverage

- package.json
> #102 - Update Database-seeder lib version

- package.json
- src/app.ts
> #000 - Adjustments

- api-docs/app_flows.drawio
- api-docs/user-diagram.drawio
> #000 - Add docs

- .husky/pre-push
- api-docs/app_flows.drawio
> docs: Update flows

- package.json
- src/controllers/user/OAuthControllers.ts
- src/routes/user/OAuthRoutes.ts
- src/routes/user/swagger.ts
- src/services/authentication/FacebookStrategy.ts
- src/services/user/OAuthServices.ts
- test/unit/controllers/user/OAuthControllers.spec.ts
- test/unit/routes/RoutesWrapper.spec.ts
- test/unit/services/user/OAuthServices.spec.ts
> #113 - Get user info with facebook ( authetication )

- package.json
> #118 Update database-management lib

- src/support/helpers/EmailSender.ts
- src/support/helpers/generateVerificationCode.ts
- src/types/Email.ts
- test/unit/support/helpers/EmailSender.spec.ts
> #126 Create verification code email method

- src/controllers/user/OAuthControllers.ts
- src/services/user/OAuthServices.ts
- test/unit/controllers/user/OAuthControllers.spec.ts
- test/unit/services/user/OAuthServices.spec.ts
> #158 - Facebook authentication to login

- src/services/authentication/LocalStrategy.ts
- test/integration/user/postLogin.spec.ts
> #190 - Add login condition

- src/controllers/user/UsersControllers.ts
- src/routes/user/userRoutes.ts
- src/services/user/UsersServices.ts
- test/integration/user/getAllUsers.spec.ts
- test/integration/user/getUser.spec.ts
- test/unit/controllers/user/UsersControllers.spec.ts
- test/unit/routes/RoutesWrapper.spec.ts
- test/unit/services/user/UsersServices.spec.ts
> #189 - Create getUser route

- src/core/dungeons&dragons5e/operations/backgrounds/GetBackgroundOperation.ts
- src/core/dungeons&dragons5e/operations/backgrounds/GetDisabledBackgroundsOperation.ts
- src/core/dungeons&dragons5e/operations/backgrounds/ToggleBackgroundsAvailabilityOperation.ts
- src/core/dungeons&dragons5e/services/backgrounds/GetAllBackgroundsService.ts
- src/core/dungeons&dragons5e/services/backgrounds/GetBackgroundService.ts
- src/core/dungeons&dragons5e/services/backgrounds/GetDisabledBackgroundsService.ts
- src/core/dungeons&dragons5e/services/backgrounds/ToggleBackgroundsAvailabilityService.ts
- src/interface/dungeons&dragons5e/presentation/armors/ArmorsController.ts
- src/interface/dungeons&dragons5e/presentation/backgrounds/BackgroundsController.ts
- src/interface/dungeons&dragons5e/presentation/backgrounds/BackgroundsRoutes.ts
- src/types/dungeons&dragons5e/contracts/core/backgrounds/GetBackground.ts
- src/types/dungeons&dragons5e/contracts/core/backgrounds/GetDisabledBackgrounds.ts
- src/types/dungeons&dragons5e/contracts/core/backgrounds/ToggleBackgroundsAvailability.ts
- src/types/dungeons&dragons5e/contracts/presentation/armors/ArmorsController.ts
- src/types/dungeons&dragons5e/contracts/presentation/backgrounds/BackgroundsController.ts
> #212 - Refactor armors and backgrounds

- tests/unit/interface/dungeons&dragons5e/presentation/armors/ArmorsController.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/armors/ArmorsRoutes.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/backgrounds/BackgroundsController.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/backgrounds/BackgroundsRoutes.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/classes/ClassesController.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/classes/ClassesRoutes.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/feats/FeatsController.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/feats/FeatsRoutes.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/gods/GodsController.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/gods/GodsRoutes.spec.ts
> #229 - Create interfaces unit tests for Armors, Backgrounds, Classes, Feats and Gods

- tests/unit/interface/dungeons&dragons5e/presentation/items/ItemsController.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/items/ItemsRoutes.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/magicItems/MagicItemsController.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/magicItems/MagicItemsRoutes.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/monsters/MonstersController.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/monsters/MonstersRoutes.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/races/RacesController.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/races/RacesRoutes.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/realms/RealmsController.spec.ts
- tests/unit/interface/dungeons&dragons5e/presentation/realms/RealmsRoutes.spec.ts
> #230 - Create interfaces unit tests for items, magicItems, monsters, races and realms

- src/infra/repositories/dungeons&dragons5e/DungeonsAndDragonsRepository.ts
- src/types/dungeons&dragons5e/contracts/repositories/dungeonsAndDragonsRepository.ts
- tests/unit/infra/repositories/dungeons&dragons5e/DungeonsAndDragonsRepository.spec.ts
- tests/unit/interface/dungeons&dragons5e/middlewares/DungeonsAndDragonsRoutesMiddleware.spec.ts
> #232 - Create infra unit tests for dungeon&dragons routes and repository

- tests/unit/domains/user/helpers/HttpRequestErrors.spec.ts
- tests/unit/domains/user/helpers/errorMessage.spec.ts
- tests/unit/domains/user/helpers/getErrorName.spec.ts
> #233 Desenvolver testes unitários - Domains

- tests/unit/domains/user/helpers/HttpStatusCode.spec.ts
- tests/unit/domains/user/helpers/newUUID.spec.ts
- tests/unit/domains/user/helpers/parametersWrapper.spec.ts
> #234 - Create domains unit tests for newUUID, HttpStatusCode and parametersWrapper

- tests/unit/core/users/operations/GetUsersOperation.spec.ts
- tests/unit/core/users/services/GetUsersService.spec.ts
> #247 - Create unit test for Core getUsers Operation and Service

- tests/unit/core/users/operations/ActivateSecretQuestionOperation.spec.ts
- tests/unit/core/users/services/ActivateSecretQuestionService.spec.ts
> #248 - Create unit tests for ActivateSecretQuestion operation and service

- tests/unit/core/users/operations/ActivateTwoFactorOperation.spec.ts
- tests/unit/core/users/services/ActivateTwoFactorService.spec.ts
> #243 - Create unit tests for ActivateTwoFactor operation and service

- tests/unit/core/users/operations/GetUserByIdOperation.spec.ts
- tests/unit/core/users/services/GetUserByIdService.spec.ts
> #246 - Create unit tests for getUserById service and operation

- .dockerignore
- tests/unit/core/users/operations/PictureProfileOperation.spec.ts
- tests/unit/core/users/services/PictureProfileService.spec.ts
> test: Create tests for upload picture

- src/core/users/operations/users/UpdatePasswordOperation.ts
- src/core/users/services/users/UpdatePasswordService.ts
- src/domains/common/helpers/parametersWrapper.ts
- src/interface/users/middlewares/AuthorizationMiddleware.ts
- src/interface/users/presentation/users/UsersController.ts
- src/interface/users/presentation/users/UsersRoutes.ts
- src/types/api/users/http/payload.d.ts
- tests/integration/users/patch/UpdatePassword.spec.ts
- tests/unit/core/dungeons&dragons5e/operations/armors/GetArmorOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/operations/armors/GetDisabledArmorsOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/services/armors/GetArmorService.spec.ts
- tests/unit/core/dungeons&dragons5e/services/armors/GetDisabledArmorsService.spec.ts
- tests/unit/interface/users/middlewares/AuthorizationMiddleware.spec.ts
- tests/unit/interface/users/presentation/users/UsersController.spec.ts
> #267 - Refactor reset password route

- src/interface/common/middlewares/AccessHeadersMiddleware.ts
- tests/unit/interface/common/middlewares/AccessHeadersMiddleware.spec.ts
> fix: Access header

- src/core/users/operations/users/LoginUserOperation.ts
- src/core/users/services/users/LoginUserService.ts
- src/domains/users/helpers/JWTGenerator.ts
- src/interface/users/presentation/users/UsersController.ts
- src/types/api/users/http/response.d.ts
- src/types/api/users/methods/index.d.ts
- src/types/modules/core/users/UserCoreDependencies.d.ts
- src/types/modules/core/users/users/LoginUser.d.ts
- src/types/modules/interface/users/presentation/users/UsersController.d.ts
- tests/integration/users/post/Login.spec.ts
- tests/unit/core/dungeons&dragons5e/operations/armors/GetAllArmorsOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/operations/classes/GetAllClassesOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/operations/classes/GetClassOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/operations/classes/GetDisabledClassesOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/services/armors/GetAllArmorsService.spec.ts
- tests/unit/core/dungeons&dragons5e/services/classes/GetClassService.spec.ts
- tests/unit/core/dungeons&dragons5e/services/classes/GetDisabledClassesService.spec.ts
- tests/unit/core/users/operations/LoginUserOperation.spec.ts
- tests/unit/core/users/services/LoginUserService.spec.ts
- tests/unit/core/users/services/LogoutUserService.spec.ts
- tests/unit/interface/users/presentation/users/UsersController.spec.ts
> #273 - Evolve login flux

- src/infra/data/campaign/campaignSeeder.json
> #290 - Create seeds for campaign

- src/infra/datafakers/dungeons&dragons5e/generators/generateDungeonsAndDragonsFaker.ts
- tests/unit/core/dungeons&dragons5e/operations/magicItems/GetDisabledMagicItemsOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/operations/magicItems/GetMagicItemOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/services/magicItems/GetDisabledMagicItemsService.spec.ts
- tests/unit/core/dungeons&dragons5e/services/magicItems/GetMagicItemService.spec.ts
> #290 - Create pending unit tests

- package.json
- src/infra/datafakers/dungeons&dragons5e/generators/generateDungeonsAndDragonsFaker.ts
- tests/unit/core/dungeons&dragons5e/operations/feats/ToggleFeatsAvailabilityOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/operations/gods/GetAllGodsOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/services/feats/ToggleFeatsAvailabilityService.spec.ts
- tests/unit/core/dungeons&dragons5e/services/gods/GetAllGodsService.spec.ts
> #285 - Create campaign types

- src/infra/data/character/characterSeeder.json
- src/infra/datafakers/dungeons&dragons5e/generators/generateDungeonsAndDragonsFaker.ts
- tests/unit/core/dungeons&dragons5e/operations/magicItems/ToggleMagicItemsAvailabilityOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/operations/monsters/GetAllMonstersOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/services/magicItems/ToggleMagicItemsAvailabilityService.spec.ts
- tests/unit/core/dungeons&dragons5e/services/monsters/GetAllMonstersService.spec.ts
> #291 - Create character seeder

- src/infra/datafakers/dungeons&dragons5e/generators/generateDungeonsAndDragonsFaker.ts
- tests/unit/core/dungeons&dragons5e/operations/feats/ToggleFeatsAvailabilityOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/operations/gods/ToggleGodsAvailabilityOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/operations/items/GetAllItemsOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/services/gods/ToggleGodsAvailabilityService.spec.ts
- tests/unit/core/dungeons&dragons5e/services/items/GetAllItemsService.spec.ts
> #287 - Create pending unit tests

- package.json
> setup: Update lib

- tests/unit/core/dungeons&dragons5e/operations/items/GetDisabledItemsOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/operations/items/GetItemOperation.spec.ts
- tests/unit/core/dungeons&dragons5e/services/items/GetDisabledItemsService.spec.ts
- tests/unit/core/dungeons&dragons5e/services/items/GetItemService.spec.ts
GetItemOperation.ts
GetDisabledItemsService.ts
GetItemService.ts
> # 288 - Creates CharactersDnd5e Model

- .husky/pre-push
- package.json
- src/domains/dungeons&dragons5e/schemas/DungeonsAndDragons5EInterfaces.ts
- src/infra/data/dungeons&dragons5e/racesSeeder.json
- src/infra/datafakers/dungeons&dragons5e/generators/generateDungeonsAndDragonsFaker.ts
> #86a3g57v3 - Add size to races schema

- .husky/pre-push
- src/infra/templates/sendCampaignInviteEmailTemplate.ts
- src/infra/templates/verifyEmailTemplate.ts
> #86a3bv94f - New email template

- .husky/pre-push
- tests/unit/core/users/operations/users/UpdateUserOperation.spec.ts
- tests/unit/core/users/operations/users/VerifyEmailOperation.spec.ts
- tests/unit/core/users/services/users/UpdateUserService.spec.ts
- tests/unit/core/users/services/users/VerifyEmailService.spec.ts
- tests/unit/interface/campaigns/CampaignsRoutesBuilder.spec.ts
> #86a3czud8 - Create missing unit tests

- package.json
> #86a3bv4vx - update database lib

- src/infra/data/dungeons&dragons5e/racesSeeder.json
> #86a3kw4dp - Create new content races

- src/interface/users/UsersRoutesBuilder.ts
- src/interface/users/middlewares/UsersRoutesMiddleware.ts
- src/types/modules/interface/common/Routes.d.ts
- tests/unit/interface/users/UsersRoutesBuilder.spec.ts
- tests/unit/interface/users/middlewares/UsersRoutesMiddleware.spec.ts
> #86a3c809z - Adjust user route object

- .github/workflows/pr-title-check.yml
> #86a3tvdqe - Adjust PR title pattern

- package.json
- src/domains/dungeons&dragons5e/schemas/DungeonsAndDragons5EInterfaces.ts
- src/infra/datafakers/dungeons&dragons5e/generators/generateDungeonsAndDragonsFaker.ts
> #86a3qg3mf - Add tale to races

- README.md
> #TR-42 - Add dot to readme ( test commit )

- src/core/campaigns/operations/PublishmentOperation.ts
- src/core/campaigns/services/PublishmentService.ts
- src/infra/datafakers/campaigns/DomainDataFaker.ts
- src/interface/campaigns/presentation/campaigns/CampaignsController.ts
- src/interface/campaigns/presentation/campaigns/CampaignsRoutes.ts
- src/interface/campaigns/presentation/campaigns/RoutesDescription.ts
- src/types/api/campaigns/http/payload.d.ts
- src/types/modules/core/campaigns/CampaignCoreDependencies.d.ts
- src/types/modules/core/campaigns/campaigns/Publishment.d.ts
- src/types/modules/interface/campaigns/presentation/campaigns/CampaignsController.d.ts
- tests/integration/campaigns/post/Publishment.spec.ts
- tests/unit/core/campaigns/operations/PublishmentOperation.spec.ts
- tests/unit/core/campaigns/services/PublishmentService.spec.ts
- tests/unit/interface/campaigns/presentation/campaigns/CampaignsController.spec.ts
> #TR-10 - Rename publishPost route

- src/infra/data/dungeons&dragons5e/racesSeeder.json
> #TR-5 - New field added to content - tales

- package.json
- src/domains/users/schemas/usersValidationSchema.ts
> #TR-62 - Add custom message to password validation

- src/infra/data/dungeons&dragons5e/classesSeeder.json
- src/infra/data/dungeons&dragons5e/racesSeeder.json
> #TR-59 - Add original flag to D&D content

- package.json
- src/infra/data/dungeons&dragons5e/racesSeeder.json
Obs.:
- As libs já foram corrigidas aprovadas e agora os campos _id desnecessários foram removidos.
- A lib populate não está mais quebrando com o raceSeeders
- Nessa PR teve atualizaçao da Db-seeders versão 5.3.3 e Bd-Management 5.0.1: links abaixo
https://github.com/TableRise/database-seeder/pull/12
https://github.com/TableRise/database-management/pull/24
> #TR-89 - Adjust seeders ded5 races ability score field

- package.json
- src/core/Application.ts
- src/core/users/operations/oauth/DiscordOperation.ts
- src/core/users/services/oauth/OAuthService.ts
- src/domains/common/helpers/HttpRequestErrors.ts
- src/interface/common/middlewares/ErrorMiddleware.ts
- src/interface/users/presentation/oauth/OAuthController.ts
- src/interface/users/presentation/oauth/OAuthRoutes.ts
- src/interface/users/strategies/DiscordStrategy.ts
- src/interface/users/strategies/GoogleStrategy.ts
- src/types/shared/errors.d.ts
- tests/unit/interface/common/middlewares/ErrorMiddleware.spec.ts
- tests/unit/interface/users/presentation/oauth/OAuthController.spec.ts
> #TR-84 - Redirect after social login

- .husky/pre-push
- .husky/pre-push.js
- .nycrc.json
- src/interface/campaigns/presentation/campaigns/CampaignsRoutes.ts
> #TR-85 - Husky improvements
